#!/usr/bin/env python3
"""
Bundle the hub into a single self-contained Lua file.

    python tools/build.py                  -> dist/hub.lua
    python tools/build.py --name "Nam Hub" --version 1.0.0

The bundle embeds every file under src/ and replaces the network-backed
HUB_REQUIRE with a table lookup, so module code is byte-identical between
the hosted build and the single-file build. Use the bundle when you want a
paste-able script or a release artifact; use loader.lua when you want to be
able to push a fix without your users re-copying anything.
"""

import argparse
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
DIST = ROOT / "dist"


def long_bracket(source: str) -> tuple[str, str]:
    """Pick a Lua long-bracket level that does not occur in the source."""
    level = 0
    while True:
        eq = "=" * level
        if f"]{eq}]" not in source and f"[{eq}[" not in source:
            return f"[{eq}[", f"]{eq}]"
        level += 1
        if level > 20:
            raise SystemExit("could not find a free long-bracket level")


def collect() -> list[tuple[str, str]]:
    files = sorted(SRC.rglob("*.lua"))
    if not files:
        raise SystemExit(f"no .lua files under {SRC}")
    out = []
    for path in files:
        module = path.relative_to(ROOT).with_suffix("").as_posix()
        out.append((module, path.read_text(encoding="utf-8")))
    return out


def build(name: str, version: str) -> str:
    parts = [
        "--[[\n"
        f"    {name} {version} - single-file build\n"
        "    Generated by tools/build.py. Do not edit; edit src/ and rebuild.\n"
        "]]\n\n",
        "local genv = (getgenv and getgenv()) or _G\n",
        "if genv.__ScriptHub and genv.__ScriptHub.Unload then pcall(genv.__ScriptHub.Unload) end\n\n",
        "local __sources = {}\n",
    ]

    for module, source in collect():
        open_b, close_b = long_bracket(source)
        parts.append(f'__sources["{module}"] = {open_b}\n{source}{close_b}\n')

    parts.append(
        "\n"
        "local __cache = {}\n"
        "local function __require(path)\n"
        "    if __cache[path] ~= nil then return __cache[path] end\n"
        "    local source = __sources[path]\n"
        "    if not source then error('[Hub] unknown module: ' .. tostring(path), 0) end\n"
        "    local chunk, err = loadstring(source, '@' .. path)\n"
        "    if not chunk then error('[Hub] syntax error in ' .. path .. ': ' .. tostring(err), 0) end\n"
        "    __cache[path] = chunk()\n"
        "    return __cache[path]\n"
        "end\n"
        "genv.HUB_REQUIRE = __require\n"
        "HUB_REQUIRE = __require\n\n"
        "local CONFIG = {\n"
        f'    Name = "{name}",\n'
        f'    Version = "{version}",\n'
        '    BaseUrl = "",\n'
        "    CacheBust = false,\n"
        "    Debug = false,\n"
        "}\n\n"
        "return __require('src/core').Start(CONFIG)\n"
    )
    return "".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", default="namdevHub")
    ap.add_argument("--version", default="1.0.0")
    ap.add_argument("--out", default=str(DIST / "hub.lua"))
    args = ap.parse_args()

    text = build(args.name, args.version)
    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")

    print(f"wrote {out} ({len(text):,} bytes, {len(collect())} modules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
