#!/usr/bin/env python3
"""Regenerate the ScriptBlox catalog section of src/registry.lua.

    python tools/refresh_catalog.py            # 40 pages, 50 games
    python tools/refresh_catalog.py --pages 80 --games 100

Everything written into the registry comes from the scriptblox public API:
game name, script, view count and last-bump date. Nothing is hand written.

Filters applied, in order:
  * scriptType == "free"      paid entries are useless without the key
  * isPatched == false        a patched script is a broken tab
  * key == false              key systems cannot be automated here
  * one entry per game        newest lastBump wins, then most views
  * ranked by views

Run it again whenever the catalog feels stale - entries carry their update
date so it is visible in the Hub tab which ones have gone quiet.
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "src" / "registry.lua"
UA = "Mozilla/5.0"

BLOCK = {"script hub", "universal", "all games", "any game", "roblox",
         "various", "multiple games", "test", "lua", "game"}
STOP = {"the", "a", "an", "of", "and", "new", "upd", "update", "code",
        "codes", "free", "beta", "alpha", "release", "testing"}

BEGIN = "    -- CATALOG BEGIN (generated by tools/refresh_catalog.py)"
END = "    -- CATALOG END"


def fetch(pages):
    out = []
    for page in range(1, pages + 1):
        url = f"https://scriptblox.com/api/script/fetch?page={page}"
        try:
            proc = subprocess.run(
                ["curl", "-sS", "-m", "25", "-H", f"User-Agent: {UA}", url],
                capture_output=True, timeout=40)
            data = json.loads(proc.stdout.decode("utf-8", errors="replace"))
            batch = data.get("result", {}).get("scripts", [])
            if not batch:
                break
            out.extend(batch)
            print(f"  page {page}: +{len(batch)} (total {len(out)})")
        except Exception as exc:
            print(f"  page {page}: failed ({exc})")
        time.sleep(0.25)
    return out


def name_match(raw):
    """Longest run of plain words: '[GEAR] Blox Fruits 3.0' -> 'blox fruits'."""
    cleaned = re.sub(r"\[[^\]]*\]", " ", raw)
    cleaned = re.sub(r"\([^\)]*\)", " ", cleaned)
    cleaned = "".join(c if (c.isascii() and (c.isalnum() or c in " '&:-")) else " "
                      for c in cleaned)
    runs, cur = [], []
    for word in cleaned.split():
        w = word.strip("-:&'").lower()
        if w and w.replace("'", "").isalnum():
            cur.append(w)
        else:
            if cur:
                runs.append(cur)
            cur = []
    if cur:
        runs.append(cur)
    if not runs:
        return None
    best = max(runs, key=lambda r: (sum(len(x) for x in r), len(r)))
    while best and best[0] in STOP:
        best = best[1:]
    while best and best[-1] in STOP:
        best = best[:-1]
    match = " ".join(best)
    return match if len(match) >= 5 else None


def lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') \
        .replace("\n", "\\n").replace("\r", "") + '"'


def display(raw):
    out = "".join(c if (c.isascii() and (c.isalnum() or c in " '&:!.-")) else ""
                  for c in raw)
    return re.sub(r"\s+", " ", out).strip(" -:") or "Script"


def build(scripts, limit):
    clean = []
    for s in scripts:
        if s.get("scriptType") != "free" or s.get("isPatched") or s.get("key"):
            continue
        game = ((s.get("game") or {}).get("name") or "").strip()
        body = (s.get("script") or "").strip()
        if not game or not body:
            continue
        clean.append({
            "game": game, "script": body,
            "title": (s.get("title") or "").strip(),
            "views": s.get("views") or 0,
            "bump": (s.get("lastBump") or s.get("createdAt") or "")[:10],
            "slug": s.get("slug") or "",
        })

    best = {}
    for c in clean:
        k = c["game"].lower()
        cur = best.get(k)
        if cur is None or (c["bump"], c["views"]) > (cur["bump"], cur["views"]):
            best[k] = c

    ranked = sorted(best.values(), key=lambda c: (-c["views"], c["bump"]))

    seen, entries = set(), []
    for g in ranked:
        nm = name_match(g["game"])
        if not nm or nm in BLOCK or nm in seen or g["game"].lower() in BLOCK:
            continue
        seen.add(nm)
        entries.append({
            "name": display(g["game"])[:46], "match": nm,
            "script": g["script"], "title": display(g["title"])[:58] or "script",
            "views": g["views"], "bump": g["bump"], "slug": g["slug"],
        })
        if len(entries) >= limit:
            break
    return entries


def render(entries):
    lines = [BEGIN]
    for e in entries:
        lines += [
            "    {",
            "        Name        = %s," % lua_str(e["name"]),
            '        Module      = "src/scripts/sbscript",',
            "        NameMatch   = %s," % lua_str(e["match"]),
            '        Icon        = "play",',
            "        Credit      = %s," % lua_str(e["title"]),
            "        ScriptTitle = %s," % lua_str(e["title"]),
            "        Updated     = %s," % lua_str(e["bump"]),
            "        Views       = %d," % e["views"],
            "        Page        = %s," % lua_str(e["slug"]),
            "        Description = %s," % lua_str(e["title"]),
            "        Script      = %s," % lua_str(e["script"]),
            "    },",
            "",
        ]
    lines.append(END)
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pages", type=int, default=40)
    ap.add_argument("--games", type=int, default=50)
    args = ap.parse_args()

    print(f"fetching {args.pages} pages from scriptblox...")
    scripts = fetch(args.pages)
    print(f"fetched {len(scripts)} entries")

    entries = build(scripts, args.games)
    print(f"kept {len(entries)} games after filtering")

    src = REGISTRY.read_text(encoding="utf-8")
    if BEGIN not in src or END not in src:
        print("ERROR: catalog markers not found in registry.lua", file=sys.stderr)
        return 1

    head = src[:src.index(BEGIN)]
    tail = src[src.index(END) + len(END):]
    REGISTRY.write_text(head + render(entries) + tail, encoding="utf-8")
    print(f"wrote {REGISTRY}")

    for i, e in enumerate(entries, 1):
        print("%3d. %-40s %s  %d views" % (i, e["name"][:40], e["bump"], e["views"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
